version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kstv-postgres
    environment:
      POSTGRES_USER: kstv_user
      POSTGRES_PASSWORD: kstv_password
      POSTGRES_DB: kstv_scoreboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: